const menuList = [
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000214',
    upper_menu_cd: 'ME10000178',
    menu_nm: '보충오더 엑셀업로드',
    menu_order: 0,
    devsc_path: '/oms/Inbound/InboundOrderExcelUpload',
    level: 1,
    path: '{보충,"보충오더 엑셀업로드"}',
    btn_group: 'excel',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000214',
    upper_menu_cd: 'ME10000178',
    menu_nm: '보충오더 엑셀업로드',
    menu_order: 0,
    devsc_path: '/oms/Inbound/InboundOrderExcelUpload',
    level: 1,
    path: '{보충,"보충오더 엑셀업로드"}',
    btn_group: 'search',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000214',
    upper_menu_cd: 'ME10000178',
    menu_nm: '보충오더 엑셀업로드',
    menu_order: 0,
    devsc_path: '/oms/Inbound/InboundOrderExcelUpload',
    level: 1,
    path: '{보충,"보충오더 엑셀업로드"}',
    btn_group: 'save',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000214',
    upper_menu_cd: 'ME10000178',
    menu_nm: '보충오더 엑셀업로드',
    menu_order: 0,
    devsc_path: '/oms/Inbound/InboundOrderExcelUpload',
    level: 1,
    path: '{보충,"보충오더 엑셀업로드"}',
    btn_group: 'init',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000202',
    upper_menu_cd: 'ME10000178',
    menu_nm: '보충오더 현황',
    menu_order: 1,
    devsc_path: '/oms/IbOrd',
    level: 1,
    path: '{보충,"보충오더 현황"}',
    btn_group: 'init',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000202',
    upper_menu_cd: 'ME10000178',
    menu_nm: '보충오더 현황',
    menu_order: 1,
    devsc_path: '/oms/IbOrd',
    level: 1,
    path: '{보충,"보충오더 현황"}',
    btn_group: 'search',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000186',
    upper_menu_cd: null,
    menu_nm: '기본 마스터 관리',
    menu_order: 1,
    devsc_path: null,
    level: 0,
    path: '{"기본 마스터 관리"}',
    btn_group: null,
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000202',
    upper_menu_cd: 'ME10000178',
    menu_nm: '보충오더 현황',
    menu_order: 1,
    devsc_path: '/oms/IbOrd',
    level: 1,
    path: '{보충,"보충오더 현황"}',
    btn_group: 'excel',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000192',
    upper_menu_cd: 'ME10000186',
    menu_nm: '화주 마스터',
    menu_order: 2,
    devsc_path: '/mdm/OwnMst',
    level: 1,
    path: '{"기본 마스터 관리","화주 마스터"}',
    btn_group: 'search',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000192',
    upper_menu_cd: 'ME10000186',
    menu_nm: '화주 마스터',
    menu_order: 2,
    devsc_path: '/mdm/OwnMst',
    level: 1,
    path: '{"기본 마스터 관리","화주 마스터"}',
    btn_group: 'excel',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000192',
    upper_menu_cd: 'ME10000186',
    menu_nm: '화주 마스터',
    menu_order: 2,
    devsc_path: '/mdm/OwnMst',
    level: 1,
    path: '{"기본 마스터 관리","화주 마스터"}',
    btn_group: 'init',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000187',
    upper_menu_cd: 'ME10000186',
    menu_nm: '상품 마스터',
    menu_order: 3,
    devsc_path: '/mdm/ItemMst',
    level: 1,
    path: '{"기본 마스터 관리","상품 마스터"}',
    btn_group: 'excel',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000187',
    upper_menu_cd: 'ME10000186',
    menu_nm: '상품 마스터',
    menu_order: 3,
    devsc_path: '/mdm/ItemMst',
    level: 1,
    path: '{"기본 마스터 관리","상품 마스터"}',
    btn_group: 'save',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000187',
    upper_menu_cd: 'ME10000186',
    menu_nm: '상품 마스터',
    menu_order: 3,
    devsc_path: '/mdm/ItemMst',
    level: 1,
    path: '{"기본 마스터 관리","상품 마스터"}',
    btn_group: 'init',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000187',
    upper_menu_cd: 'ME10000186',
    menu_nm: '상품 마스터',
    menu_order: 3,
    devsc_path: '/mdm/ItemMst',
    level: 1,
    path: '{"기본 마스터 관리","상품 마스터"}',
    btn_group: 'search',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME00000010',
    upper_menu_cd: null,
    menu_nm: '기본 마스터 관리',
    menu_order: 10,
    devsc_path: '',
    level: 0,
    path: '{"기본 마스터 관리"}',
    btn_group: null,
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000213',
    upper_menu_cd: 'ME10000193',
    menu_nm: '출고오더 엑셀업로드',
    menu_order: 10,
    devsc_path: '/oms/Outbound/OutboundOrderExcelUpload',
    level: 1,
    path: '{출고,"출고오더 엑셀업로드"}',
    btn_group: 'search',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000199',
    upper_menu_cd: 'ME10000198',
    menu_nm: '재고 현황',
    menu_order: 10,
    devsc_path: '/oms/StockMgt',
    level: 1,
    path: '{재고,"재고 현황"}',
    btn_group: 'init',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000199',
    upper_menu_cd: 'ME10000198',
    menu_nm: '재고 현황',
    menu_order: 10,
    devsc_path: '/oms/StockMgt',
    level: 1,
    path: '{재고,"재고 현황"}',
    btn_group: 'search',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000213',
    upper_menu_cd: 'ME10000193',
    menu_nm: '출고오더 엑셀업로드',
    menu_order: 10,
    devsc_path: '/oms/Outbound/OutboundOrderExcelUpload',
    level: 1,
    path: '{출고,"출고오더 엑셀업로드"}',
    btn_group: 'init',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000179',
    upper_menu_cd: 'ME10000178',
    menu_nm: '[작업자용] 보충오더 검수',
    menu_order: 10,
    devsc_path: '/oms/IbOrdInsp',
    level: 1,
    path: '{보충,"[작업자용] 보충오더 검수"}',
    btn_group: 'init',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000179',
    upper_menu_cd: 'ME10000178',
    menu_nm: '[작업자용] 보충오더 검수',
    menu_order: 10,
    devsc_path: '/oms/IbOrdInsp',
    level: 1,
    path: '{보충,"[작업자용] 보충오더 검수"}',
    btn_group: 'search',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000217',
    upper_menu_cd: 'ME10000216',
    menu_nm: 'AGV존 모니터링',
    menu_order: 10,
    devsc_path: '/oms/Monitoring/AGVZone',
    level: 1,
    path: '{모니터링,"AGV존 모니터링"}',
    btn_group: null,
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000199',
    upper_menu_cd: 'ME10000198',
    menu_nm: '재고 현황',
    menu_order: 10,
    devsc_path: '/oms/StockMgt',
    level: 1,
    path: '{재고,"재고 현황"}',
    btn_group: 'excel',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000213',
    upper_menu_cd: 'ME10000193',
    menu_nm: '출고오더 엑셀업로드',
    menu_order: 10,
    devsc_path: '/oms/Outbound/OutboundOrderExcelUpload',
    level: 1,
    path: '{출고,"출고오더 엑셀업로드"}',
    btn_group: 'save',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000213',
    upper_menu_cd: 'ME10000193',
    menu_nm: '출고오더 엑셀업로드',
    menu_order: 10,
    devsc_path: '/oms/Outbound/OutboundOrderExcelUpload',
    level: 1,
    path: '{출고,"출고오더 엑셀업로드"}',
    btn_group: 'excel',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000154',
    upper_menu_cd: null,
    menu_nm: '인프라',
    menu_order: 10,
    devsc_path: null,
    level: 0,
    path: '{인프라}',
    btn_group: null,
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000155',
    upper_menu_cd: 'ME10000154',
    menu_nm: '센터 관리',
    menu_order: 11,
    devsc_path: '/inf/Center',
    level: 1,
    path: '{인프라,"센터 관리"}',
    btn_group: 'save',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000155',
    upper_menu_cd: 'ME10000154',
    menu_nm: '센터 관리',
    menu_order: 11,
    devsc_path: '/inf/Center',
    level: 1,
    path: '{인프라,"센터 관리"}',
    btn_group: 'add',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000155',
    upper_menu_cd: 'ME10000154',
    menu_nm: '센터 관리',
    menu_order: 11,
    devsc_path: '/inf/Center',
    level: 1,
    path: '{인프라,"센터 관리"}',
    btn_group: 'search',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000155',
    upper_menu_cd: 'ME10000154',
    menu_nm: '센터 관리',
    menu_order: 11,
    devsc_path: '/inf/Center',
    level: 1,
    path: '{인프라,"센터 관리"}',
    btn_group: 'excel',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000155',
    upper_menu_cd: 'ME10000154',
    menu_nm: '센터 관리',
    menu_order: 11,
    devsc_path: '/inf/Center',
    level: 1,
    path: '{인프라,"센터 관리"}',
    btn_group: 'delete',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000155',
    upper_menu_cd: 'ME10000154',
    menu_nm: '센터 관리',
    menu_order: 11,
    devsc_path: '/inf/Center',
    level: 1,
    path: '{인프라,"센터 관리"}',
    btn_group: 'init',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000156',
    upper_menu_cd: 'ME10000154',
    menu_nm: '존 관리',
    menu_order: 12,
    devsc_path: '/inf/Zone',
    level: 1,
    path: '{인프라,"존 관리"}',
    btn_group: 'add',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000156',
    upper_menu_cd: 'ME10000154',
    menu_nm: '존 관리',
    menu_order: 12,
    devsc_path: '/inf/Zone',
    level: 1,
    path: '{인프라,"존 관리"}',
    btn_group: 'search',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000156',
    upper_menu_cd: 'ME10000154',
    menu_nm: '존 관리',
    menu_order: 12,
    devsc_path: '/inf/Zone',
    level: 1,
    path: '{인프라,"존 관리"}',
    btn_group: 'init',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000156',
    upper_menu_cd: 'ME10000154',
    menu_nm: '존 관리',
    menu_order: 12,
    devsc_path: '/inf/Zone',
    level: 1,
    path: '{인프라,"존 관리"}',
    btn_group: 'excel',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000156',
    upper_menu_cd: 'ME10000154',
    menu_nm: '존 관리',
    menu_order: 12,
    devsc_path: '/inf/Zone',
    level: 1,
    path: '{인프라,"존 관리"}',
    btn_group: 'delete',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000156',
    upper_menu_cd: 'ME10000154',
    menu_nm: '존 관리',
    menu_order: 12,
    devsc_path: '/inf/Zone',
    level: 1,
    path: '{인프라,"존 관리"}',
    btn_group: 'save',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000158',
    upper_menu_cd: 'ME10000154',
    menu_nm: '스테이션 관리',
    menu_order: 13,
    devsc_path: '/inf/Station',
    level: 1,
    path: '{인프라,"스테이션 관리"}',
    btn_group: 'save',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000158',
    upper_menu_cd: 'ME10000154',
    menu_nm: '스테이션 관리',
    menu_order: 13,
    devsc_path: '/inf/Station',
    level: 1,
    path: '{인프라,"스테이션 관리"}',
    btn_group: 'delete',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000158',
    upper_menu_cd: 'ME10000154',
    menu_nm: '스테이션 관리',
    menu_order: 13,
    devsc_path: '/inf/Station',
    level: 1,
    path: '{인프라,"스테이션 관리"}',
    btn_group: 'excel',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000158',
    upper_menu_cd: 'ME10000154',
    menu_nm: '스테이션 관리',
    menu_order: 13,
    devsc_path: '/inf/Station',
    level: 1,
    path: '{인프라,"스테이션 관리"}',
    btn_group: 'init',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000158',
    upper_menu_cd: 'ME10000154',
    menu_nm: '스테이션 관리',
    menu_order: 13,
    devsc_path: '/inf/Station',
    level: 1,
    path: '{인프라,"스테이션 관리"}',
    btn_group: 'add',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000158',
    upper_menu_cd: 'ME10000154',
    menu_nm: '스테이션 관리',
    menu_order: 13,
    devsc_path: '/inf/Station',
    level: 1,
    path: '{인프라,"스테이션 관리"}',
    btn_group: 'search',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000157',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'Shelf 타입 관리',
    menu_order: 14,
    devsc_path: '/inf/ShelfType',
    level: 1,
    path: '{인프라,"Shelf 타입 관리"}',
    btn_group: 'add',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000157',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'Shelf 타입 관리',
    menu_order: 14,
    devsc_path: '/inf/ShelfType',
    level: 1,
    path: '{인프라,"Shelf 타입 관리"}',
    btn_group: 'init',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000157',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'Shelf 타입 관리',
    menu_order: 14,
    devsc_path: '/inf/ShelfType',
    level: 1,
    path: '{인프라,"Shelf 타입 관리"}',
    btn_group: 'delete',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000157',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'Shelf 타입 관리',
    menu_order: 14,
    devsc_path: '/inf/ShelfType',
    level: 1,
    path: '{인프라,"Shelf 타입 관리"}',
    btn_group: 'search',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000157',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'Shelf 타입 관리',
    menu_order: 14,
    devsc_path: '/inf/ShelfType',
    level: 1,
    path: '{인프라,"Shelf 타입 관리"}',
    btn_group: 'excel',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000157',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'Shelf 타입 관리',
    menu_order: 14,
    devsc_path: '/inf/ShelfType',
    level: 1,
    path: '{인프라,"Shelf 타입 관리"}',
    btn_group: 'save',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000209',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'Shelf 관리',
    menu_order: 15,
    devsc_path: '/inf/Shelf',
    level: 1,
    path: '{인프라,"Shelf 관리"}',
    btn_group: 'init',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000209',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'Shelf 관리',
    menu_order: 15,
    devsc_path: '/inf/Shelf',
    level: 1,
    path: '{인프라,"Shelf 관리"}',
    btn_group: 'search',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000209',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'Shelf 관리',
    menu_order: 15,
    devsc_path: '/inf/Shelf',
    level: 1,
    path: '{인프라,"Shelf 관리"}',
    btn_group: 'delete',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000209',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'Shelf 관리',
    menu_order: 15,
    devsc_path: '/inf/Shelf',
    level: 1,
    path: '{인프라,"Shelf 관리"}',
    btn_group: 'add',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000209',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'Shelf 관리',
    menu_order: 15,
    devsc_path: '/inf/Shelf',
    level: 1,
    path: '{인프라,"Shelf 관리"}',
    btn_group: 'excel',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000209',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'Shelf 관리',
    menu_order: 15,
    devsc_path: '/inf/Shelf',
    level: 1,
    path: '{인프라,"Shelf 관리"}',
    btn_group: 'save',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000159',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'AGV 관리',
    menu_order: 16,
    devsc_path: '/inf/AGV',
    level: 1,
    path: '{인프라,"AGV 관리"}',
    btn_group: 'save',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000159',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'AGV 관리',
    menu_order: 16,
    devsc_path: '/inf/AGV',
    level: 1,
    path: '{인프라,"AGV 관리"}',
    btn_group: 'search',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000159',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'AGV 관리',
    menu_order: 16,
    devsc_path: '/inf/AGV',
    level: 1,
    path: '{인프라,"AGV 관리"}',
    btn_group: 'add',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000159',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'AGV 관리',
    menu_order: 16,
    devsc_path: '/inf/AGV',
    level: 1,
    path: '{인프라,"AGV 관리"}',
    btn_group: 'excel',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000159',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'AGV 관리',
    menu_order: 16,
    devsc_path: '/inf/AGV',
    level: 1,
    path: '{인프라,"AGV 관리"}',
    btn_group: 'delete',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000159',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'AGV 관리',
    menu_order: 16,
    devsc_path: '/inf/AGV',
    level: 1,
    path: '{인프라,"AGV 관리"}',
    btn_group: 'init',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000160',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'AGV 충전기 관리',
    menu_order: 17,
    devsc_path: '/inf/AGVCharger',
    level: 1,
    path: '{인프라,"AGV 충전기 관리"}',
    btn_group: 'delete',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000160',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'AGV 충전기 관리',
    menu_order: 17,
    devsc_path: '/inf/AGVCharger',
    level: 1,
    path: '{인프라,"AGV 충전기 관리"}',
    btn_group: 'search',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000160',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'AGV 충전기 관리',
    menu_order: 17,
    devsc_path: '/inf/AGVCharger',
    level: 1,
    path: '{인프라,"AGV 충전기 관리"}',
    btn_group: 'excel',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000160',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'AGV 충전기 관리',
    menu_order: 17,
    devsc_path: '/inf/AGVCharger',
    level: 1,
    path: '{인프라,"AGV 충전기 관리"}',
    btn_group: 'init',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000160',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'AGV 충전기 관리',
    menu_order: 17,
    devsc_path: '/inf/AGVCharger',
    level: 1,
    path: '{인프라,"AGV 충전기 관리"}',
    btn_group: 'add',
  },
  {
    app_cd: 'INF',
    menu_cd: 'ME10000160',
    upper_menu_cd: 'ME10000154',
    menu_nm: 'AGV 충전기 관리',
    menu_order: 17,
    devsc_path: '/inf/AGVCharger',
    level: 1,
    path: '{인프라,"AGV 충전기 관리"}',
    btn_group: 'save',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000184',
    upper_menu_cd: 'ME10000178',
    menu_nm: '[작업자용] 보충오더 할당',
    menu_order: 20,
    devsc_path: '/oms/Assignment',
    level: 1,
    path: '{보충,"[작업자용] 보충오더 할당"}',
    btn_group: 'excel',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000218',
    upper_menu_cd: 'ME10000198',
    menu_nm: '재고 조사',
    menu_order: 20,
    devsc_path: '/oms/Stocktaking',
    level: 1,
    path: '{재고,"재고 조사"}',
    btn_group: 'excel',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000184',
    upper_menu_cd: 'ME10000178',
    menu_nm: '[작업자용] 보충오더 할당',
    menu_order: 20,
    devsc_path: '/oms/Assignment',
    level: 1,
    path: '{보충,"[작업자용] 보충오더 할당"}',
    btn_group: 'search',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME00000020',
    upper_menu_cd: null,
    menu_nm: '사용자 마스터 관리',
    menu_order: 20,
    devsc_path: '',
    level: 0,
    path: '{"사용자 마스터 관리"}',
    btn_group: null,
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000184',
    upper_menu_cd: 'ME10000178',
    menu_nm: '[작업자용] 보충오더 할당',
    menu_order: 20,
    devsc_path: '/oms/Assignment',
    level: 1,
    path: '{보충,"[작업자용] 보충오더 할당"}',
    btn_group: 'init',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000184',
    upper_menu_cd: 'ME10000178',
    menu_nm: '[작업자용] 보충오더 할당',
    menu_order: 20,
    devsc_path: '/oms/Assignment',
    level: 1,
    path: '{보충,"[작업자용] 보충오더 할당"}',
    btn_group: 'add',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000203',
    upper_menu_cd: 'ME10000193',
    menu_nm: '출고오더 현황',
    menu_order: 20,
    devsc_path: '/oms/Outbound/OutboundOrderStatus',
    level: 1,
    path: '{출고,"출고오더 현황"}',
    btn_group: 'search',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000218',
    upper_menu_cd: 'ME10000198',
    menu_nm: '재고 조사',
    menu_order: 20,
    devsc_path: '/oms/Stocktaking',
    level: 1,
    path: '{재고,"재고 조사"}',
    btn_group: 'search',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000184',
    upper_menu_cd: 'ME10000178',
    menu_nm: '[작업자용] 보충오더 할당',
    menu_order: 20,
    devsc_path: '/oms/Assignment',
    level: 1,
    path: '{보충,"[작업자용] 보충오더 할당"}',
    btn_group: 'delete',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000219',
    upper_menu_cd: 'ME10000216',
    menu_nm: '재고 모니터링',
    menu_order: 20,
    devsc_path: '/oms/Monitoring/Inventory',
    level: 1,
    path: '{모니터링,"재고 모니터링"}',
    btn_group: null,
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000218',
    upper_menu_cd: 'ME10000198',
    menu_nm: '재고 조사',
    menu_order: 20,
    devsc_path: '/oms/Stocktaking',
    level: 1,
    path: '{재고,"재고 조사"}',
    btn_group: 'save',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000203',
    upper_menu_cd: 'ME10000193',
    menu_nm: '출고오더 현황',
    menu_order: 20,
    devsc_path: '/oms/Outbound/OutboundOrderStatus',
    level: 1,
    path: '{출고,"출고오더 현황"}',
    btn_group: 'init',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000184',
    upper_menu_cd: 'ME10000178',
    menu_nm: '[작업자용] 보충오더 할당',
    menu_order: 20,
    devsc_path: '/oms/Assignment',
    level: 1,
    path: '{보충,"[작업자용] 보충오더 할당"}',
    btn_group: 'save',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000218',
    upper_menu_cd: 'ME10000198',
    menu_nm: '재고 조사',
    menu_order: 20,
    devsc_path: '/oms/Stocktaking',
    level: 1,
    path: '{재고,"재고 조사"}',
    btn_group: 'init',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME00000030',
    upper_menu_cd: null,
    menu_nm: '메뉴 마스터 관리',
    menu_order: 30,
    devsc_path: '',
    level: 0,
    path: '{"메뉴 마스터 관리"}',
    btn_group: null,
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000185',
    upper_menu_cd: 'ME10000178',
    menu_nm: '[작업자용] 보충오더 적치',
    menu_order: 30,
    devsc_path: '/oms/Stockpiling',
    level: 1,
    path: '{보충,"[작업자용] 보충오더 적치"}',
    btn_group: 'delete',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000185',
    upper_menu_cd: 'ME10000178',
    menu_nm: '[작업자용] 보충오더 적치',
    menu_order: 30,
    devsc_path: '/oms/Stockpiling',
    level: 1,
    path: '{보충,"[작업자용] 보충오더 적치"}',
    btn_group: 'init',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000194',
    upper_menu_cd: 'ME10000193',
    menu_nm: '[작업자용] 출고오더 분배',
    menu_order: 30,
    devsc_path: '/oms/Outbound/Distribution',
    level: 1,
    path: '{출고,"[작업자용] 출고오더 분배"}',
    btn_group: 'search',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000185',
    upper_menu_cd: 'ME10000178',
    menu_nm: '[작업자용] 보충오더 적치',
    menu_order: 30,
    devsc_path: '/oms/Stockpiling',
    level: 1,
    path: '{보충,"[작업자용] 보충오더 적치"}',
    btn_group: 'search',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000185',
    upper_menu_cd: 'ME10000178',
    menu_nm: '[작업자용] 보충오더 적치',
    menu_order: 30,
    devsc_path: '/oms/Stockpiling',
    level: 1,
    path: '{보충,"[작업자용] 보충오더 적치"}',
    btn_group: 'save',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000194',
    upper_menu_cd: 'ME10000193',
    menu_nm: '[작업자용] 출고오더 분배',
    menu_order: 30,
    devsc_path: '/oms/Outbound/Distribution',
    level: 1,
    path: '{출고,"[작업자용] 출고오더 분배"}',
    btn_group: 'excel',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000185',
    upper_menu_cd: 'ME10000178',
    menu_nm: '[작업자용] 보충오더 적치',
    menu_order: 30,
    devsc_path: '/oms/Stockpiling',
    level: 1,
    path: '{보충,"[작업자용] 보충오더 적치"}',
    btn_group: 'add',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000185',
    upper_menu_cd: 'ME10000178',
    menu_nm: '[작업자용] 보충오더 적치',
    menu_order: 30,
    devsc_path: '/oms/Stockpiling',
    level: 1,
    path: '{보충,"[작업자용] 보충오더 적치"}',
    btn_group: 'excel',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000194',
    upper_menu_cd: 'ME10000193',
    menu_nm: '[작업자용] 출고오더 분배',
    menu_order: 30,
    devsc_path: '/oms/Outbound/Distribution',
    level: 1,
    path: '{출고,"[작업자용] 출고오더 분배"}',
    btn_group: 'init',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000196',
    upper_menu_cd: 'ME10000193',
    menu_nm: '[작업자용] 출고오더 할당',
    menu_order: 40,
    devsc_path: '/oms/Outbound/Assignment',
    level: 1,
    path: '{출고,"[작업자용] 출고오더 할당"}',
    btn_group: 'save',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000196',
    upper_menu_cd: 'ME10000193',
    menu_nm: '[작업자용] 출고오더 할당',
    menu_order: 40,
    devsc_path: '/oms/Outbound/Assignment',
    level: 1,
    path: '{출고,"[작업자용] 출고오더 할당"}',
    btn_group: 'init',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000196',
    upper_menu_cd: 'ME10000193',
    menu_nm: '[작업자용] 출고오더 할당',
    menu_order: 40,
    devsc_path: '/oms/Outbound/Assignment',
    level: 1,
    path: '{출고,"[작업자용] 출고오더 할당"}',
    btn_group: 'search',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000196',
    upper_menu_cd: 'ME10000193',
    menu_nm: '[작업자용] 출고오더 할당',
    menu_order: 40,
    devsc_path: '/oms/Outbound/Assignment',
    level: 1,
    path: '{출고,"[작업자용] 출고오더 할당"}',
    btn_group: 'excel',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME00000040',
    upper_menu_cd: null,
    menu_nm: '권한 마스터 관리',
    menu_order: 40,
    devsc_path: '',
    level: 0,
    path: '{"권한 마스터 관리"}',
    btn_group: null,
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000204',
    upper_menu_cd: null,
    menu_nm: 'I/F내역',
    menu_order: 50,
    devsc_path: '',
    level: 0,
    path: '{I/F내역}',
    btn_group: null,
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000200',
    upper_menu_cd: 'ME10000193',
    menu_nm: '[작업자용] 출고오더 피킹',
    menu_order: 50,
    devsc_path: '/oms/Picking',
    level: 1,
    path: '{출고,"[작업자용] 출고오더 피킹"}',
    btn_group: null,
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000001',
    upper_menu_cd: 'ME00000010',
    menu_nm: '어플리케이션',
    menu_order: 100,
    devsc_path: '/cms/Application',
    level: 1,
    path: '{"기본 마스터 관리",어플리케이션}',
    btn_group: 'save',
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000178',
    upper_menu_cd: null,
    menu_nm: '보충',
    menu_order: 100,
    devsc_path: null,
    level: 0,
    path: '{보충}',
    btn_group: null,
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000001',
    upper_menu_cd: 'ME00000010',
    menu_nm: '어플리케이션',
    menu_order: 100,
    devsc_path: '/cms/Application',
    level: 1,
    path: '{"기본 마스터 관리",어플리케이션}',
    btn_group: 'init',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000001',
    upper_menu_cd: 'ME00000010',
    menu_nm: '어플리케이션',
    menu_order: 100,
    devsc_path: '/cms/Application',
    level: 1,
    path: '{"기본 마스터 관리",어플리케이션}',
    btn_group: 'search',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000001',
    upper_menu_cd: 'ME00000010',
    menu_nm: '어플리케이션',
    menu_order: 100,
    devsc_path: '/cms/Application',
    level: 1,
    path: '{"기본 마스터 관리",어플리케이션}',
    btn_group: 'delete',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000001',
    upper_menu_cd: 'ME00000010',
    menu_nm: '어플리케이션',
    menu_order: 100,
    devsc_path: '/cms/Application',
    level: 1,
    path: '{"기본 마스터 관리",어플리케이션}',
    btn_group: 'add',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000205',
    upper_menu_cd: 'ME10000204',
    menu_nm: '화주 수신내역',
    menu_order: 101,
    devsc_path: '/cms/IntfOwner',
    level: 1,
    path: '{I/F내역,"화주 수신내역"}',
    btn_group: 'search',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000002',
    upper_menu_cd: 'ME00000030',
    menu_nm: '개발화면',
    menu_order: 101,
    devsc_path: '/cms/DevelopmentScreen',
    level: 1,
    path: '{"메뉴 마스터 관리",개발화면}',
    btn_group: 'add',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000205',
    upper_menu_cd: 'ME10000204',
    menu_nm: '화주 수신내역',
    menu_order: 101,
    devsc_path: '/cms/IntfOwner',
    level: 1,
    path: '{I/F내역,"화주 수신내역"}',
    btn_group: 'init',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000002',
    upper_menu_cd: 'ME00000030',
    menu_nm: '개발화면',
    menu_order: 101,
    devsc_path: '/cms/DevelopmentScreen',
    level: 1,
    path: '{"메뉴 마스터 관리",개발화면}',
    btn_group: 'search',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000002',
    upper_menu_cd: 'ME00000030',
    menu_nm: '개발화면',
    menu_order: 101,
    devsc_path: '/cms/DevelopmentScreen',
    level: 1,
    path: '{"메뉴 마스터 관리",개발화면}',
    btn_group: 'delete',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000002',
    upper_menu_cd: 'ME00000030',
    menu_nm: '개발화면',
    menu_order: 101,
    devsc_path: '/cms/DevelopmentScreen',
    level: 1,
    path: '{"메뉴 마스터 관리",개발화면}',
    btn_group: 'save',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000002',
    upper_menu_cd: 'ME00000030',
    menu_nm: '개발화면',
    menu_order: 101,
    devsc_path: '/cms/DevelopmentScreen',
    level: 1,
    path: '{"메뉴 마스터 관리",개발화면}',
    btn_group: 'init',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000003',
    upper_menu_cd: 'ME00000030',
    menu_nm: '메뉴',
    menu_order: 102,
    devsc_path: '/cms/Menu',
    level: 1,
    path: '{"메뉴 마스터 관리",메뉴}',
    btn_group: 'search',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000206',
    upper_menu_cd: 'ME10000204',
    menu_nm: '상품 수신내역',
    menu_order: 102,
    devsc_path: '/cms/IntfItemC',
    level: 1,
    path: '{I/F내역,"상품 수신내역"}',
    btn_group: 'init',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000003',
    upper_menu_cd: 'ME00000030',
    menu_nm: '메뉴',
    menu_order: 102,
    devsc_path: '/cms/Menu',
    level: 1,
    path: '{"메뉴 마스터 관리",메뉴}',
    btn_group: 'save',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000003',
    upper_menu_cd: 'ME00000030',
    menu_nm: '메뉴',
    menu_order: 102,
    devsc_path: '/cms/Menu',
    level: 1,
    path: '{"메뉴 마스터 관리",메뉴}',
    btn_group: 'add',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000003',
    upper_menu_cd: 'ME00000030',
    menu_nm: '메뉴',
    menu_order: 102,
    devsc_path: '/cms/Menu',
    level: 1,
    path: '{"메뉴 마스터 관리",메뉴}',
    btn_group: 'init',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000003',
    upper_menu_cd: 'ME00000030',
    menu_nm: '메뉴',
    menu_order: 102,
    devsc_path: '/cms/Menu',
    level: 1,
    path: '{"메뉴 마스터 관리",메뉴}',
    btn_group: 'delete',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000206',
    upper_menu_cd: 'ME10000204',
    menu_nm: '상품 수신내역',
    menu_order: 102,
    devsc_path: '/cms/IntfItemC',
    level: 1,
    path: '{I/F내역,"상품 수신내역"}',
    btn_group: 'search',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000207',
    upper_menu_cd: 'ME10000204',
    menu_nm: '보충오더 수신내역',
    menu_order: 103,
    devsc_path: '/cms/IntfInbound',
    level: 1,
    path: '{I/F내역,"보충오더 수신내역"}',
    btn_group: 'init',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000004',
    upper_menu_cd: 'ME00000010',
    menu_nm: '시스템코드',
    menu_order: 103,
    devsc_path: '/cms/SystemCode',
    level: 1,
    path: '{"기본 마스터 관리",시스템코드}',
    btn_group: 'add',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000004',
    upper_menu_cd: 'ME00000010',
    menu_nm: '시스템코드',
    menu_order: 103,
    devsc_path: '/cms/SystemCode',
    level: 1,
    path: '{"기본 마스터 관리",시스템코드}',
    btn_group: 'delete',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000004',
    upper_menu_cd: 'ME00000010',
    menu_nm: '시스템코드',
    menu_order: 103,
    devsc_path: '/cms/SystemCode',
    level: 1,
    path: '{"기본 마스터 관리",시스템코드}',
    btn_group: 'update',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000004',
    upper_menu_cd: 'ME00000010',
    menu_nm: '시스템코드',
    menu_order: 103,
    devsc_path: '/cms/SystemCode',
    level: 1,
    path: '{"기본 마스터 관리",시스템코드}',
    btn_group: 'init',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000004',
    upper_menu_cd: 'ME00000010',
    menu_nm: '시스템코드',
    menu_order: 103,
    devsc_path: '/cms/SystemCode',
    level: 1,
    path: '{"기본 마스터 관리",시스템코드}',
    btn_group: 'search',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000207',
    upper_menu_cd: 'ME10000204',
    menu_nm: '보충오더 수신내역',
    menu_order: 103,
    devsc_path: '/cms/IntfInbound',
    level: 1,
    path: '{I/F내역,"보충오더 수신내역"}',
    btn_group: 'search',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000005',
    upper_menu_cd: 'ME00000020',
    menu_nm: '사용자',
    menu_order: 104,
    devsc_path: '/cms/User',
    level: 1,
    path: '{"사용자 마스터 관리",사용자}',
    btn_group: 'update',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000005',
    upper_menu_cd: 'ME00000020',
    menu_nm: '사용자',
    menu_order: 104,
    devsc_path: '/cms/User',
    level: 1,
    path: '{"사용자 마스터 관리",사용자}',
    btn_group: 'add',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000005',
    upper_menu_cd: 'ME00000020',
    menu_nm: '사용자',
    menu_order: 104,
    devsc_path: '/cms/User',
    level: 1,
    path: '{"사용자 마스터 관리",사용자}',
    btn_group: 'delete',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000208',
    upper_menu_cd: 'ME10000204',
    menu_nm: '출고오더 수신내역',
    menu_order: 104,
    devsc_path: '/cms/IntfOutbound',
    level: 1,
    path: '{I/F내역,"출고오더 수신내역"}',
    btn_group: 'search',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000005',
    upper_menu_cd: 'ME00000020',
    menu_nm: '사용자',
    menu_order: 104,
    devsc_path: '/cms/User',
    level: 1,
    path: '{"사용자 마스터 관리",사용자}',
    btn_group: 'search',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000208',
    upper_menu_cd: 'ME10000204',
    menu_nm: '출고오더 수신내역',
    menu_order: 104,
    devsc_path: '/cms/IntfOutbound',
    level: 1,
    path: '{I/F내역,"출고오더 수신내역"}',
    btn_group: 'init',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000005',
    upper_menu_cd: 'ME00000020',
    menu_nm: '사용자',
    menu_order: 104,
    devsc_path: '/cms/User',
    level: 1,
    path: '{"사용자 마스터 관리",사용자}',
    btn_group: 'init',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000006',
    upper_menu_cd: 'ME00000010',
    menu_nm: '메시지',
    menu_order: 105,
    devsc_path: '/cms/Message',
    level: 1,
    path: '{"기본 마스터 관리",메시지}',
    btn_group: 'delete',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000006',
    upper_menu_cd: 'ME00000010',
    menu_nm: '메시지',
    menu_order: 105,
    devsc_path: '/cms/Message',
    level: 1,
    path: '{"기본 마스터 관리",메시지}',
    btn_group: 'init',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000006',
    upper_menu_cd: 'ME00000010',
    menu_nm: '메시지',
    menu_order: 105,
    devsc_path: '/cms/Message',
    level: 1,
    path: '{"기본 마스터 관리",메시지}',
    btn_group: 'save',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000006',
    upper_menu_cd: 'ME00000010',
    menu_nm: '메시지',
    menu_order: 105,
    devsc_path: '/cms/Message',
    level: 1,
    path: '{"기본 마스터 관리",메시지}',
    btn_group: 'search',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000006',
    upper_menu_cd: 'ME00000010',
    menu_nm: '메시지',
    menu_order: 105,
    devsc_path: '/cms/Message',
    level: 1,
    path: '{"기본 마스터 관리",메시지}',
    btn_group: 'add',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000008',
    upper_menu_cd: 'ME00000010',
    menu_nm: '회사',
    menu_order: 106,
    devsc_path: '/cms/Company',
    level: 1,
    path: '{"기본 마스터 관리",회사}',
    btn_group: 'search',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000008',
    upper_menu_cd: 'ME00000010',
    menu_nm: '회사',
    menu_order: 106,
    devsc_path: '/cms/Company',
    level: 1,
    path: '{"기본 마스터 관리",회사}',
    btn_group: 'update',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000008',
    upper_menu_cd: 'ME00000010',
    menu_nm: '회사',
    menu_order: 106,
    devsc_path: '/cms/Company',
    level: 1,
    path: '{"기본 마스터 관리",회사}',
    btn_group: 'delete',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000008',
    upper_menu_cd: 'ME00000010',
    menu_nm: '회사',
    menu_order: 106,
    devsc_path: '/cms/Company',
    level: 1,
    path: '{"기본 마스터 관리",회사}',
    btn_group: 'add',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000008',
    upper_menu_cd: 'ME00000010',
    menu_nm: '회사',
    menu_order: 106,
    devsc_path: '/cms/Company',
    level: 1,
    path: '{"기본 마스터 관리",회사}',
    btn_group: 'init',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000009',
    upper_menu_cd: 'ME00000010',
    menu_nm: '회사별 어플리케이션',
    menu_order: 108,
    devsc_path: '/cms/CompanyApplication',
    level: 1,
    path: '{"기본 마스터 관리","회사별 어플리케이션"}',
    btn_group: 'search',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000009',
    upper_menu_cd: 'ME00000010',
    menu_nm: '회사별 어플리케이션',
    menu_order: 108,
    devsc_path: '/cms/CompanyApplication',
    level: 1,
    path: '{"기본 마스터 관리","회사별 어플리케이션"}',
    btn_group: 'update',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000009',
    upper_menu_cd: 'ME00000010',
    menu_nm: '회사별 어플리케이션',
    menu_order: 108,
    devsc_path: '/cms/CompanyApplication',
    level: 1,
    path: '{"기본 마스터 관리","회사별 어플리케이션"}',
    btn_group: 'init',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000010',
    upper_menu_cd: 'ME00000030',
    menu_nm: '버튼',
    menu_order: 109,
    devsc_path: '/cms/Button',
    level: 1,
    path: '{"메뉴 마스터 관리",버튼}',
    btn_group: 'search',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000215',
    upper_menu_cd: 'ME00000010',
    menu_nm: 'TEST',
    menu_order: 109,
    devsc_path: '/cms/Test2',
    level: 1,
    path: '{"기본 마스터 관리",TEST}',
    btn_group: 'add',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000215',
    upper_menu_cd: 'ME00000010',
    menu_nm: 'TEST',
    menu_order: 109,
    devsc_path: '/cms/Test2',
    level: 1,
    path: '{"기본 마스터 관리",TEST}',
    btn_group: 'search',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000010',
    upper_menu_cd: 'ME00000030',
    menu_nm: '버튼',
    menu_order: 109,
    devsc_path: '/cms/Button',
    level: 1,
    path: '{"메뉴 마스터 관리",버튼}',
    btn_group: 'add',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000010',
    upper_menu_cd: 'ME00000030',
    menu_nm: '버튼',
    menu_order: 109,
    devsc_path: '/cms/Button',
    level: 1,
    path: '{"메뉴 마스터 관리",버튼}',
    btn_group: 'delete',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000010',
    upper_menu_cd: 'ME00000030',
    menu_nm: '버튼',
    menu_order: 109,
    devsc_path: '/cms/Button',
    level: 1,
    path: '{"메뉴 마스터 관리",버튼}',
    btn_group: 'save',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000010',
    upper_menu_cd: 'ME00000030',
    menu_nm: '버튼',
    menu_order: 109,
    devsc_path: '/cms/Button',
    level: 1,
    path: '{"메뉴 마스터 관리",버튼}',
    btn_group: 'init',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000180',
    upper_menu_cd: 'ME10000150',
    menu_nm: 'ROLE 관리',
    menu_order: 110,
    devsc_path: '/cms/Role',
    level: 2,
    path: '{"권한 마스터 관리","사용자 권한 관리","ROLE 관리"}',
    btn_group: 'search',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000013',
    upper_menu_cd: 'ME10000140',
    menu_nm: 'ROLE별 어플리케이션',
    menu_order: 110,
    devsc_path: '/cms/RoleApplication',
    level: 2,
    path: '{"권한 마스터 관리","ROLE 관리","ROLE별 어플리케이션"}',
    btn_group: 'search',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000180',
    upper_menu_cd: 'ME10000150',
    menu_nm: 'ROLE 관리',
    menu_order: 110,
    devsc_path: '/cms/Role',
    level: 2,
    path: '{"권한 마스터 관리","사용자 권한 관리","ROLE 관리"}',
    btn_group: 'init',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000013',
    upper_menu_cd: 'ME10000140',
    menu_nm: 'ROLE별 어플리케이션',
    menu_order: 110,
    devsc_path: '/cms/RoleApplication',
    level: 2,
    path: '{"권한 마스터 관리","ROLE 관리","ROLE별 어플리케이션"}',
    btn_group: 'init',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000013',
    upper_menu_cd: 'ME10000140',
    menu_nm: 'ROLE별 어플리케이션',
    menu_order: 110,
    devsc_path: '/cms/RoleApplication',
    level: 2,
    path: '{"권한 마스터 관리","ROLE 관리","ROLE별 어플리케이션"}',
    btn_group: 'update',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000180',
    upper_menu_cd: 'ME10000150',
    menu_nm: 'ROLE 관리',
    menu_order: 110,
    devsc_path: '/cms/Role',
    level: 2,
    path: '{"권한 마스터 관리","사용자 권한 관리","ROLE 관리"}',
    btn_group: 'delete',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000180',
    upper_menu_cd: 'ME10000150',
    menu_nm: 'ROLE 관리',
    menu_order: 110,
    devsc_path: '/cms/Role',
    level: 2,
    path: '{"권한 마스터 관리","사용자 권한 관리","ROLE 관리"}',
    btn_group: 'add',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000180',
    upper_menu_cd: 'ME10000150',
    menu_nm: 'ROLE 관리',
    menu_order: 110,
    devsc_path: '/cms/Role',
    level: 2,
    path: '{"권한 마스터 관리","사용자 권한 관리","ROLE 관리"}',
    btn_group: 'save',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000011',
    upper_menu_cd: 'ME10000140',
    menu_nm: 'ROLE별 메뉴',
    menu_order: 111,
    devsc_path: '/cms/RoleMenu',
    level: 2,
    path: '{"권한 마스터 관리","ROLE 관리","ROLE별 메뉴"}',
    btn_group: 'init',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000011',
    upper_menu_cd: 'ME10000140',
    menu_nm: 'ROLE별 메뉴',
    menu_order: 111,
    devsc_path: '/cms/RoleMenu',
    level: 2,
    path: '{"권한 마스터 관리","ROLE 관리","ROLE별 메뉴"}',
    btn_group: 'save',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000011',
    upper_menu_cd: 'ME10000140',
    menu_nm: 'ROLE별 메뉴',
    menu_order: 111,
    devsc_path: '/cms/RoleMenu',
    level: 2,
    path: '{"권한 마스터 관리","ROLE 관리","ROLE별 메뉴"}',
    btn_group: 'search',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000014',
    upper_menu_cd: 'ME10000150',
    menu_nm: '사용자별 ROLE',
    menu_order: 113,
    devsc_path: '/cms/UserRole',
    level: 2,
    path: '{"권한 마스터 관리","사용자 권한 관리","사용자별 ROLE"}',
    btn_group: 'update',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000012',
    upper_menu_cd: 'ME10000140',
    menu_nm: 'ROLE별 버튼',
    menu_order: 113,
    devsc_path: '/cms/RoleButton',
    level: 2,
    path: '{"권한 마스터 관리","ROLE 관리","ROLE별 버튼"}',
    btn_group: 'update',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000012',
    upper_menu_cd: 'ME10000140',
    menu_nm: 'ROLE별 버튼',
    menu_order: 113,
    devsc_path: '/cms/RoleButton',
    level: 2,
    path: '{"권한 마스터 관리","ROLE 관리","ROLE별 버튼"}',
    btn_group: 'search',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000014',
    upper_menu_cd: 'ME10000150',
    menu_nm: '사용자별 ROLE',
    menu_order: 113,
    devsc_path: '/cms/UserRole',
    level: 2,
    path: '{"권한 마스터 관리","사용자 권한 관리","사용자별 ROLE"}',
    btn_group: 'search',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000012',
    upper_menu_cd: 'ME10000140',
    menu_nm: 'ROLE별 버튼',
    menu_order: 113,
    devsc_path: '/cms/RoleButton',
    level: 2,
    path: '{"권한 마스터 관리","ROLE 관리","ROLE별 버튼"}',
    btn_group: 'init',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000014',
    upper_menu_cd: 'ME10000150',
    menu_nm: '사용자별 ROLE',
    menu_order: 113,
    devsc_path: '/cms/UserRole',
    level: 2,
    path: '{"권한 마스터 관리","사용자 권한 관리","사용자별 ROLE"}',
    btn_group: 'init',
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000150',
    upper_menu_cd: 'ME00000040',
    menu_nm: '사용자 권한 관리',
    menu_order: 141,
    devsc_path: '',
    level: 1,
    path: '{"권한 마스터 관리","사용자 권한 관리"}',
    btn_group: null,
  },
  {
    app_cd: 'CMS',
    menu_cd: 'ME10000140',
    upper_menu_cd: 'ME00000040',
    menu_nm: 'ROLE 관리',
    menu_order: 142,
    devsc_path: '',
    level: 1,
    path: '{"권한 마스터 관리","ROLE 관리"}',
    btn_group: null,
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000193',
    upper_menu_cd: null,
    menu_nm: '출고',
    menu_order: 200,
    devsc_path: '/oms/Outbound',
    level: 0,
    path: '{출고}',
    btn_group: null,
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000198',
    upper_menu_cd: null,
    menu_nm: '재고',
    menu_order: 300,
    devsc_path: null,
    level: 0,
    path: '{재고}',
    btn_group: null,
  },
  {
    app_cd: 'OMS',
    menu_cd: 'ME10000216',
    upper_menu_cd: null,
    menu_nm: '모니터링',
    menu_order: 400,
    devsc_path: '',
    level: 0,
    path: '{모니터링}',
    btn_group: null,
  },
];

export function getUpperMenu(appCd) {
  let resultList = [];

  menuList
    .filter(menu => menu.upper_menu_cd == null && menu.app_cd === appCd)
    .forEach(m => {
      recursiveMenuList(m, resultList);
      //treeMenuList(m, resultList);
    });

  return resultList;
}
/* 메뉴 트리구조화 */
function recursiveMenuList(parent, seed) {
  /* 상위 메뉴 코드로 자식메뉴 filter */
  let children = menuList.filter(mm => mm.upper_menu_cd == parent.menu_cd);

  /* Root 객체에 데이터 쌓기 */
  seed.push(parent);

  /* 자식 메뉴가 존재 할시 버튼 합치기 및 재귀 */
  if (children != null && children.length > 0) {
    /* 메뉴별 버튼 합치기 */
    children = btnMenuList(children);

    /* devsc_path로 route.js에 추가 */
    createRoute(children.flatMap(m => m.devsc_path || []));

    /* 자식메뉴 하위에 메뉴가 존재하는지 재귀   */
    let results = [];
    children.forEach(m => {
      recursiveMenuList(m, results);
    });
    parent.children = results;
  }
}

/* 메뉴별 버튼 Array 변수로 합치기 */
function btnMenuList(childBtnList) {
  return childBtnList.filter((m, i, arr) => {
    m.btnList = arr.flatMap(mm =>
      mm.menu_cd == m.menu_cd ? mm.btn_group : [],
    );
    return arr.findIndex(menu => menu.menu_cd == m.menu_cd) === i;
  });
}

import routes from '@/router/routes';
// import route from '@/router/index';
import { useRoute } from 'vue-router';
import * as vue from 'vue';
import * as router from 'vue-router';
import * as quasar from 'quasar';

console.dir(vue);
console.info('router', router);
console.info('quasar', quasar);

const route = useRoute();

export function createRoute(path) {
  if (typeof path === 'string') {
    if (!routes.find(route => route.path == path))
      routes.push({
        path: path,
        component: () => import('views/cms/Message.vue'),
      });
    console.log(routes);
  }

  if (typeof path === 'object') {
  }

  if (Array.isArray(path)) {
    path.forEach(p => {
      if (p.path || typeof p === 'string') {
        createRoute(p.path || p);
      }
    });
  }
}
/* 메뉴 조회 */
export function getMenus() {
  return menuList;
}
